apiVersion: v1
kind: Pod
metadata:
  name: teste-secret
spec:
  containers:
  - image: busybox
    name: teste-secret
    command:
      - sleep
      - "3600"
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: teste-secret
          key: user
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: teste-secret
          key: password