apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc-demo
      mountPath: /usr/share/nginx/html
  volumes:
    - name: pvc-demo
      persistentVolumeClaim:
        claimName: pvc-demo
